# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02798e4a6d150b32d97c4ee5849f29e7bca7672606d2628a1e36564ed5a40799ed44a558d1f6802388966e088cf6a39bb618bee5212a825069107f2f8e208d73

test:
  secret_key_base: fb813e34a330561b08d683a53884aa5f4fe94e149f0d4df1ddfde2416b5332ca2870441d9ab0f95909a402ddcdd4462e002cb6a13481dc02bf1359329ce5af87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
